# Generated by Django 5.0.4 on 2024-05-27 14:56

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),  
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiciosCategoria',
            new_name='Servicios',
        ),
        migrations.AddField(
            model_name='servicios',
            name='valor',
            field=models.FloatField(default=0.0),  
            preserve_default=False,
        ),
    ]
