# Generated by Django 5.0.4 on 2024-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20240527_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'Nuestros Servicios', 'verbose_name_plural': 'Nuestros Servicios'},
        ),
        migrations.AddField(
            model_name='servicios',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(max_length=300, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='valor',
            field=models.IntegerField(verbose_name='valor (CLP)'),
        ),
    ]
