# Generated by Django 5.0.4 on 2024-05-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicios_options_servicios_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='descripción'),
        ),
    ]
