# Generated by Django 5.0.4 on 2024-05-28 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='vendedor',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Vendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
