# Generated by Django 5.0.4 on 2024-05-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0002_alter_comunidad_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
    ]
