# Generated by Django 5.0.4 on 2024-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0003_remove_usuario_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(unique=True),
        ),
    ]
